version: "3.9"

services:
    eugenecad:
        container_name: eugenecad
        image: eugenecad
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8080:8080"
            - "8443:8443"
