name: Build and Publish

on:
  # run it during pull request
  pull_request:
    branches: [production]

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHA_PAT }}
      
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and push to registry
          docker build -t nonasoftware/eugenecad:$IMAGE_TAG -t ghcr.io/nonasoftware/eugenecad:$IMAGE_TAG .
          docker push nonasoftware/eugenecad:$IMAGE_TAG
          docker push ghcr.io/nonasoftware/eugenecad:$IMAGE_TAG
          echo "::set-output name=image::nonasoftware/eugenecad:$IMAGE_TAG"
